# $schema: https://raw.githubusercontent.com/picamator/transfer-object/main/schema/config.schema.json

generator:
  transferNamespace: "Picamator\\Examples\\TransferObject\\Generated\\TransferGenerator"
  transferPath: "${PROJECT_ROOT}/examples/Generated/TransferGenerator"
  definitionPath: "${PROJECT_ROOT}/examples/config/transfer-generator/definition"
