Credentials:
  login:
    type: string
    required:
    protected:
  token:
    type: string
    required:
    protected:
  createdAt:
    dateTimeType: "\\DateTimeImmutable"
    required:
    protected:
  updatedAt:
    dateTimeType: "\\DateTime"
    required:
