# $schema: ./../../../../schema/config.schema.json
generator:
  transferNamespace: "Picamator\\Doc\\Samples\\TransferObject\\Generated\\TransferGenerator"
  transferPath: "${PROJECT_ROOT}/doc/samples/Generated/TransferGenerator"
  definitionPath: "${PROJECT_ROOT}/doc/samples/config/transfer-generator/definition"
