#!/usr/bin/env php
<?php declare(strict_types = 1);

if (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use Picamator\TransferObject\Command\TransferGeneratorCommand;
use Symfony\Component\Console\Application;

$application = new Application('echo', '1.0.0');
$command = new TransferGeneratorCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
