# $schema: https://raw.githubusercontent.com/picamator/transfer-object/refs/heads/main/schema/definition.schema.json

# Product
Product:
  sku:
    type: string
  name:
    type: string
  price:
    type: float
  currency:
    type: string
  stock:
    type: int
  isDiscounted:
    type: bool
  deliveryOptions:
    collectionType: DeliveryOptions
  details:
    type: Details
  stores:
    type: array
  labels:
    type: Labels
  availabilities:
    collectionType: Availabilities
  measurementUnit:
    type: MeasurementUnit

# DeliveryOptions
DeliveryOptions:
  name:
    type: string

# Details
Details:
  description:
    type: string
  isRegional:
    type: bool

# Labels
Labels:
  sale:
    type: string

# Availabilities
Availabilities:
  total:
    type: int
  buffer:
    type: int

# MeasurementUnit
MeasurementUnit:
  palette:
    type: Palette
  box:
    type: Box

# Palette
Palette:
  type:
    type: string
  items:
    type: int

# Box
Box:
  type:
    type: string
  items:
    type: int

