name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature Request]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please take a moment to fill out this form to help us better understand your request.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Please provide a clear and concise description of the feature or enhancement you’d like to see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and use case
      description: Explain why this feature is important and how it will be used. What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: |
        Optional: Have you considered any alternative solutions or features? Please describe them.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Optional: Provide any other context, screenshots, or code examples related to the feature request.
    validations:
      required: false
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/picamator/transfer-object/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
