#!/usr/bin/env bash

# function to wrap text in green
function wrap_in_green() {
  echo -e "\e[32m$1\e[0m"
}

# function to wrap text in yellow
function wrap_in_yellow() {
  echo -e "\e[33m$1\e[0m"
}

# function to display usage
function show_usage() {
  wrap_in_green "==================================="
  wrap_in_green "    Transfer Object (Docker SDK)   "
  wrap_in_green "==================================="
  echo -n "Usage: "
  wrap_in_yellow "$0 [-x] [-p] <command> [args]"
  echo
  echo "Options:"
  echo -e "  $(wrap_in_yellow "-x")    Enable Xdebug with debug + coverage mode when starting containers"
  echo -e "  $(wrap_in_yellow "-p")    Enable Xdebug with profiler mode when starting containers"
  echo
  echo "Commands:"
  echo -e "  $(wrap_in_yellow "build")                      Build Docker containers"
  echo -e "  $(wrap_in_yellow "start")                      Start Docker containers (honors -x / -p)"
  echo -e "  $(wrap_in_yellow "stop")                       Stop Docker containers"
  echo -e "  $(wrap_in_yellow "cli")                        Open container shell or execute the PHP script when provided as an argument"
  echo -e "  $(wrap_in_yellow "composer <command>")         Run composer command"
  echo -e "  $(wrap_in_yellow "phpstan")                    Run PHPStan"
  echo -e "  $(wrap_in_yellow "phpunit")                    Run all PHPUnit tests or concrete test case when full qualified name provided as an argument"
  echo -e "  $(wrap_in_yellow "phpunit-group <group>")      Run PHPUnit tests assigned to the group"
  echo -e "  $(wrap_in_yellow "phpcs")                      Run PHP CodeSniffer"
  echo -e "  $(wrap_in_yellow "phpcbf")                     Run PHP Code Beautifier and Fixer"
  echo -e "  $(wrap_in_yellow "hook-install")               Install CaptainHook"
  echo -e "  $(wrap_in_yellow "hook <command>")             Run CaptainHook command"
  echo -e "  $(wrap_in_yellow "to-generate")                Generate internal transfer objects or externals when configuration path provided as an argument"
  echo -e "  $(wrap_in_yellow "to-generate-bulk")           Generate bulk internal transfer objects or externals when configuration path provided as an argument"
  echo -e "  $(wrap_in_yellow "df-generate")                Generate definition"
  echo
  echo "Examples:"
  echo -e "  $(wrap_in_yellow "$0 -x start")                Start containers with Xdebug (debug + coverage)"
  echo -e "  $(wrap_in_yellow "$0 -p start")                Start containers with Xdebug profiler"
  echo -e "  $(wrap_in_yellow "$0 composer install")        Run composer install inside container"
}

# vars
DOCKER_CONTAINER_NAME=transfer-object-php
DOCKER_EXEC="docker exec -it ${DOCKER_CONTAINER_NAME}"

# options
XDEBUG_MODE=''

while getopts ":xp" opt; do
  case ${opt} in
    x )
      XDEBUG_MODE="debug,coverage"
      ;;
    p )
      XDEBUG_MODE="profile"
      ;;
    \? )
      show_usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

# arguments
case $1 in
  build)
    USER_ID=$(id -u) GROUP_ID=$(id -g) docker compose build
    ;;
  start)
    if [ "$XDEBUG_MODE" == "" ]; then
      docker compose up -d --remove-orphans
    else
      XDEBUG_MODE={$XDEBUG_MODE} docker compose up -d --remove-orphans
    fi
    ;;
  stop)
    docker compose stop
    ;;
  cli)
    if [ -n "$2" ]; then
      $DOCKER_EXEC php -f $2
    else
      $DOCKER_EXEC bash
    fi
    ;;
  composer)
    if [ -n "$5" ]; then
      $DOCKER_EXEC composer "$2" "$3" "$4" "$5"
    elif [ -n "$4" ]; then
      $DOCKER_EXEC composer "$2" "$3" "$4"
    elif [ -n "$3" ]; then
      $DOCKER_EXEC composer "$2" "$3"
    else
      $DOCKER_EXEC composer "$2"
    fi
    ;;
  phpstan)
    $DOCKER_EXEC composer phpstan
    ;;
  phpunit)
    if [ -n "$2" ]; then
      $DOCKER_EXEC composer phpunit -- --filter $2
    else
      $DOCKER_EXEC composer phpunit
    fi
    ;;
  phpunit-group)
    $DOCKER_EXEC composer phpunit-group $2
    ;;
  phpcs)
    $DOCKER_EXEC composer phpcs
    ;;
  phpcbf)
    $DOCKER_EXEC composer phpcbf
    ;;
  hook-install)
    $DOCKER_EXEC composer captainhook install --only-enabled --run-mode=docker --run-exec="docker exec -i $DOCKER_CONTAINER_NAME"
    ;;
  hook)
    $DOCKER_EXEC composer captainhook $2
    ;;
  to-generate)
    if [ -n "$2" ]; then
      $DOCKER_EXEC composer transfer-generate -- -c $2 -v
    else
      $DOCKER_EXEC composer transfer-generate -- -c ./config/generator.config.yml -v
    fi
    ;;
  to-generate-bulk)
    if [ -n "$2" ]; then
      $DOCKER_EXEC composer transfer-generate-bulk -- -b $2
    else
      $DOCKER_EXEC composer transfer-generate-bulk -- -b ./var/config/config.list.txt
    fi
    ;;
  df-generate)
     $DOCKER_EXEC composer definition-generate
    ;;
  *)
    show_usage
    exit 0
    ;;
esac
