Template:
  className:
    type: string
  classNamespace:
    type: string
  imports:
    type: array
  properties:
    type: array
  propertiesCount:
    type: int
  metaConstants:
    type: array
  attributes:
    type: array
  dockBlocks:
    type: array
