generator:
  transferNamespace: "Picamator\\TransferObject\\Generated"
  transferPath: "/home/transfer/transfer-object/src/TransferObject/Generated"
  definitionPath: "/home/transfer/transfer-object/config/definition"
