# $schema: ./../schema/config.schema.json
generator:
  transferNamespace: "Picamator\\TransferObject\\Generated"
  transferPath: "${PROJECT_ROOT}/src/Generated"
  definitionPath: "${PROJECT_ROOT}/config/definition"
