# $schema: https://raw.githubusercontent.com/picamator/transfer-object/main/schema/definition.schema.json

AdvancedCustomer:
  customer:
    type: "Picamator\\Examples\\TransferObject\\Generated\\TransferGenerator\\CustomerTransfer"
  address:
    type: "Picamator\\Examples\\TransferObject\\Advanced\\AddressData"
  credentials:
    type: "Picamator\\Examples\\TransferObject\\Advanced\\CredentialsData"
