Config:
  classNamespace:
    type: string
  definitionPath:
    type: DefinitionPath
  generatedPath:
    type: GeneratedPath

DefinitionPath:
  path:
    type: string

GeneratedPath:
  path:
    type: string
