Definition:
  content:
    type: DefinitionContent
  validator:
    type: DefinitionValidator

DefinitionContent:
  className:
    type: string
  properties:
    collectionType: DefinitionProperty

DefinitionProperty:
  propertyName:
    type: string
  buildInType:
    type: string
  transferType:
    type: string
  collectionType:
    type: string

DefinitionValidator:
  isValid:
    type: bool
  errorMessages:
    collectionType: ValidatorMessage

Generator:
  definitionKey:
    type: string
  validator:
    type: DefinitionValidator
