Helper:
  definitionPath:
    type: string
  content:
    type: HelperContent

HelperContent:
  className:
    type: string
  content:
    type: array

HelperFilesystem:
  fileName:
    type: string
  definitionPath:
    type: string
  content:
    type: string
