# $schema: ./../../schema/definition.schema.json
Validator:
  isValid:
    type: bool
    required:
  errorMessages:
    collectionType: ValidatorMessage

ValidatorMessage:
  isValid:
    type: bool
    required:
    protected:
  errorMessage:
    type: string
    required:
    protected:
