Template:
  className:
    type: string
    required:
  classNamespace:
    type: string
    required:
  imports:
    type: ArrayObject
  properties:
    type: ArrayObject
  propertiesCount:
    type: int
    required:
  metaConstants:
    type: ArrayObject
  attributes:
    type: ArrayObject
  dockBlocks:
    type: ArrayObject
  nullables:
    type: ArrayObject
